# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FavoriteBooks', '0002_auto_20190422_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploadBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookUploaded', to='FavoriteBooks.User'),
        ),
    ]
